# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Propensity score match from Rcpp
#' @name ps_matchCPP
#' @return A list with two vectors (`match_id`, `match_x`).
#' @param x a numeric vector
#' @export
ps_matchCPP <- function(x) {
    .Call(`_egpkg_ps_matchCPP`, x)
}

#' Hello world from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @examples
#' rcpp_hello_world()
#' @export
rcpp_hello_world <- function() {
    .Call(`_egpkg_rcpp_hello_world`)
}

